# Generated by Django 5.1.7 on 2025-04-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_customerlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerlogin',
        ),
    ]
